version: '3'
services:
  education-fe:
    container_name: 'education-fe'
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:3000
